'use client';

import { useMemo, useState } from 'react';

const product = {"repo":"ThreatPulse","suite":"Cybersecurity Suite","category":"Threat intelligence","audience":"blue-team leads, SOC managers, and founders protecting revenue","promise":"translate threat signals into daily decisions, not noisy feeds","inputLabel":"Asset, industry, or threat concern","placeholder":"SaaS startup exposed admin panels and credential stuffing risk","primary":"Generate pulse","gradient":"from-rose-300 via-orange-300 to-amber-300","modules":["Signal clustering","Business impact scoring","Mitigation shortlist","Executive summary","Watchlist memory"],"outputs":["Top threat theme","Business impact","Next defensive action","Watchlist update"],"next":["OTX/URLhaus feed fusion","industry watchlists","automated morning SOC brief","MITRE ATT&CK mapping"]} as const;
type Intelligence = { confidence: number; urgency: string; immediate_outputs: Array<{ title: string; detail: string; priority: string }>; automation_plan: Array<{ stage: number; module: string; value: string }>; future_addons: Array<{ name: string; horizon: string; contributor_lane: string }>; contributor_brief: string };
function scoreFrom(input: string) { const seed = input.trim().length || 18; return Math.min(96, 54 + (seed % 37)); }
export default function Home() {
  const [input, setInput] = useState('');
  const [intel, setIntel] = useState<Intelligence | null>(null);
  const [loading, setLoading] = useState(false);
  const score = useMemo(() => intel?.confidence || scoreFrom(input || product.placeholder), [input, intel]);
  const subject = input.trim() || product.placeholder;
  async function runIntel() { setLoading(true); try { const response = await fetch('/api/intelligence', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ input: subject }) }); setIntel(await response.json()); } finally { setLoading(false); } }
  return (
    <main className="min-h-screen bg-[#080a0f] text-white selection:bg-white selection:text-black">
      <section className="relative overflow-hidden border-b border-white/10"><div className={`absolute inset-0 bg-gradient-to-br ${product.gradient} opacity-20 blur-3xl`} /><nav className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><div><p className="text-[10px] font-black uppercase tracking-[0.36em] text-white/45">{product.suite}</p><h1 className="text-xl font-black tracking-tight sm:text-2xl">{product.repo}</h1></div><div className="hidden items-center gap-6 text-sm text-white/65 md:flex"><a href="#ai">AI Engine</a><a href="#future">Future Stack</a><a href="#contributors">Contributors</a><a href="#try" className="rounded-full bg-white px-4 py-2 font-bold text-black">Try live</a></div></nav>
      <div className="relative z-10 mx-auto grid max-w-7xl gap-10 px-5 pb-16 pt-10 sm:px-8 lg:grid-cols-[1.05fr_0.95fr] lg:pb-24 lg:pt-16"><div><p className="w-fit rounded-full border border-white/15 bg-white/10 px-4 py-2 text-[11px] font-black uppercase tracking-[0.24em] text-white/70">{product.category}</p><h2 className="mt-7 max-w-4xl text-5xl font-black leading-[0.95] tracking-[-0.04em] sm:text-7xl lg:text-8xl">{product.promise}</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-white/68">Built for {product.audience}. Open-source by design, AI-native by default, and ready for contributors who want to build tools future generations can actually use.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a href="#try" className="rounded-full bg-white px-6 py-4 text-center text-sm font-black text-black shadow-2xl shadow-white/10">{product.primary}</a><a href="#contributors" className="rounded-full border border-white/15 px-6 py-4 text-center text-sm font-bold text-white/80">Contribute intelligence</a></div></div>
      <div id="try" className="rounded-[2rem] border border-white/10 bg-white/[0.07] p-4 shadow-2xl shadow-black/40 backdrop-blur-xl sm:p-6"><div className="rounded-[1.5rem] border border-white/10 bg-black/40 p-5"><div className="flex items-center justify-between gap-4"><div><p className="text-[10px] font-black uppercase tracking-[0.28em] text-white/45">AI command panel</p><h3 className="mt-2 text-2xl font-black">Run product intelligence</h3></div><div className="rounded-full bg-white px-4 py-2 text-sm font-black text-black">{score}%</div></div><label className="mt-7 block text-sm font-bold text-white/70">{product.inputLabel}</label><textarea value={input} onChange={(event) => setInput(event.target.value)} placeholder={product.placeholder} className="mt-3 min-h-36 w-full resize-none rounded-3xl border border-white/10 bg-white/[0.06] p-4 text-sm leading-6 text-white outline-none placeholder:text-white/32 focus:border-white/30" /><button onClick={runIntel} className="mt-4 w-full rounded-full bg-white px-5 py-4 text-sm font-black text-black">{loading ? 'Thinking...' : product.primary}</button><div className="mt-5 rounded-3xl border border-white/10 bg-white/[0.05] p-5"><p className="text-[10px] font-black uppercase tracking-[0.28em] text-white/40">Result preview</p><h4 className="mt-3 text-xl font-black">{intel ? intel.immediate_outputs[0].title : product.outputs[0]}</h4><p className="mt-3 text-sm leading-6 text-white/60">Input: {subject.slice(0, 92)}</p></div></div></div></div></section>
      <section id="ai" className="mx-auto grid max-w-7xl gap-8 px-5 py-16 sm:px-8 lg:grid-cols-[0.75fr_1.25fr]"><div><p className="text-[10px] font-black uppercase tracking-[0.32em] text-white/40">AI-native engine</p><h2 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl">The product has a brain, not just a homepage.</h2><p className="mt-5 text-base leading-7 text-white/58">The API route returns structured outputs, automation stages, future add-ons, and contributor lanes. It can later connect to Groq, Supabase memory, or domain APIs without rewriting the product surface.</p></div><div className="grid gap-4 sm:grid-cols-2">{(intel?.automation_plan || product.modules.map((module, index) => ({ stage: index + 1, module, value: 'Ready for contributor expansion.' }))).map((item) => <article key={item.module} className="rounded-3xl border border-white/10 bg-white/[0.045] p-5"><p className="text-xs font-black text-white/35">0{item.stage}</p><h3 className="mt-4 text-xl font-black">{item.module}</h3><p className="mt-3 text-sm leading-6 text-white/55">{item.value}</p></article>)}</div></section>
      <section id="future" className="border-y border-white/10 bg-white/[0.035]"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><p className="text-[10px] font-black uppercase tracking-[0.32em] text-white/40">Future generation add-ons</p><div className="mt-6 grid gap-4 md:grid-cols-4">{(intel?.future_addons || product.next.map((name, index) => ({ name, horizon: index < 2 ? 'v2' : 'v3', contributor_lane: 'product intelligence' }))).map((addon) => <div key={addon.name} className="rounded-3xl border border-white/10 bg-black/30 p-5"><p className="text-xs font-black uppercase tracking-[0.22em] text-white/35">{addon.horizon} / {addon.contributor_lane}</p><h3 className="mt-5 text-lg font-black">{addon.name}</h3></div>)}</div></div></section>
      <section id="contributors" className="mx-auto max-w-7xl px-5 py-16 sm:px-8"><div className="rounded-[2rem] border border-white/10 bg-white/[0.06] p-6 sm:p-8"><p className="text-[10px] font-black uppercase tracking-[0.32em] text-white/40">Contributor mission</p><h2 className="mt-4 text-4xl font-black tracking-tight">Build tools that make life easier in the AI era.</h2><p className="mt-4 max-w-3xl text-base leading-7 text-white/58">{intel?.contributor_brief || 'Contributors can improve product intelligence, integrations, memory, accessibility, tests, and workflows.'}</p></div></section>
    </main>
  );
}
